// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: led_control.proto

package com.paperatus.matrix.proto;

public final class LedControlProto {
  private LedControlProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paperatus_LedData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paperatus_LedData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021led_control.proto\022\tpaperatus\032\033google/p" +
      "rotobuf/empty.proto\032\036google/protobuf/wra" +
      "ppers.proto\"6\n\007LedData\022\014\n\004data\030\001 \001(\014\022\r\n\005" +
      "width\030\002 \001(\r\022\016\n\006height\030\003 \001(\r2\207\001\n\nLedContr" +
      "ol\022>\n\nInitialize\022\022.paperatus.LedData\032\032.g" +
      "oogle.protobuf.BoolValue\"\000\0229\n\tWriteData\022" +
      "\022.paperatus.LedData\032\026.google.protobuf.Em" +
      "pty\"\000B/\n\032com.paperatus.matrix.protoB\017Led" +
      "ControlProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_paperatus_LedData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_paperatus_LedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paperatus_LedData_descriptor,
        new java.lang.String[] { "Data", "Width", "Height", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
