// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: led_control.proto

package com.paperatus.matrix.proto;

public interface LedDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paperatus.LedData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>uint32 width = 2;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>uint32 height = 3;</code>
   * @return The height.
   */
  int getHeight();
}
