// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: led_control.proto

package com.paperatus.matrix.proto;

public interface MappingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paperatus.Mapping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated uint32 data = 1;</code>
   * @return A list containing the data.
   */
  java.util.List<java.lang.Integer> getDataList();
  /**
   * <code>repeated uint32 data = 1;</code>
   * @return The count of data.
   */
  int getDataCount();
  /**
   * <code>repeated uint32 data = 1;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  int getData(int index);
}
