//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: led_control.proto

package com.paperatus.matrix.proto;

@kotlin.jvm.JvmSynthetic
public inline fun mapping(block: com.paperatus.matrix.proto.MappingKt.Dsl.() -> kotlin.Unit): com.paperatus.matrix.proto.Mapping =
  com.paperatus.matrix.proto.MappingKt.Dsl._create(com.paperatus.matrix.proto.Mapping.newBuilder()).apply { block() }._build()
public object MappingKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.paperatus.matrix.proto.Mapping.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.paperatus.matrix.proto.Mapping.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.paperatus.matrix.proto.Mapping = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated uint32 data = 1;</code>
     */
     public val data: com.google.protobuf.kotlin.DslList<kotlin.Int, DataProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDataList()
      )
    /**
     * <code>repeated uint32 data = 1;</code>
     * @param value The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addData")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, DataProxy>.add(value: kotlin.Int) {
      _builder.addData(value)
    }/**
     * <code>repeated uint32 data = 1;</code>
     * @param value The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, DataProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * <code>repeated uint32 data = 1;</code>
     * @param values The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllData")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, DataProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllData(values)
    }/**
     * <code>repeated uint32 data = 1;</code>
     * @param values The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, DataProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * <code>repeated uint32 data = 1;</code>
     * @param index The index to set the value at.
     * @param value The data to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setData")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, DataProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setData(index, value)
    }/**
     * <code>repeated uint32 data = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearData")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, DataProxy>.clear() {
      _builder.clearData()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.paperatus.matrix.proto.Mapping.copy(block: com.paperatus.matrix.proto.MappingKt.Dsl.() -> kotlin.Unit): com.paperatus.matrix.proto.Mapping =
  com.paperatus.matrix.proto.MappingKt.Dsl._create(this.toBuilder()).apply { block() }._build()
