// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: led_control.proto

package com.paperatus.matrix.proto;

/**
 * Protobuf type {@code paperatus.Setup}
 */
public final class Setup extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:paperatus.Setup)
    SetupOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Setup.newBuilder() to construct.
  private Setup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Setup() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Setup();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Setup(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.paperatus.matrix.proto.LedData.Builder subBuilder = null;
            if (ledData_ != null) {
              subBuilder = ledData_.toBuilder();
            }
            ledData_ = input.readMessage(com.paperatus.matrix.proto.LedData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ledData_);
              ledData_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.paperatus.matrix.proto.Mapping.Builder subBuilder = null;
            if (mapping_ != null) {
              subBuilder = mapping_.toBuilder();
            }
            mapping_ = input.readMessage(com.paperatus.matrix.proto.Mapping.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mapping_);
              mapping_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.paperatus.matrix.proto.LedControlProto.internal_static_paperatus_Setup_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.paperatus.matrix.proto.LedControlProto.internal_static_paperatus_Setup_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.paperatus.matrix.proto.Setup.class, com.paperatus.matrix.proto.Setup.Builder.class);
  }

  public static final int LEDDATA_FIELD_NUMBER = 1;
  private com.paperatus.matrix.proto.LedData ledData_;
  /**
   * <code>.paperatus.LedData ledData = 1;</code>
   * @return Whether the ledData field is set.
   */
  @java.lang.Override
  public boolean hasLedData() {
    return ledData_ != null;
  }
  /**
   * <code>.paperatus.LedData ledData = 1;</code>
   * @return The ledData.
   */
  @java.lang.Override
  public com.paperatus.matrix.proto.LedData getLedData() {
    return ledData_ == null ? com.paperatus.matrix.proto.LedData.getDefaultInstance() : ledData_;
  }
  /**
   * <code>.paperatus.LedData ledData = 1;</code>
   */
  @java.lang.Override
  public com.paperatus.matrix.proto.LedDataOrBuilder getLedDataOrBuilder() {
    return getLedData();
  }

  public static final int MAPPING_FIELD_NUMBER = 2;
  private com.paperatus.matrix.proto.Mapping mapping_;
  /**
   * <code>.paperatus.Mapping mapping = 2;</code>
   * @return Whether the mapping field is set.
   */
  @java.lang.Override
  public boolean hasMapping() {
    return mapping_ != null;
  }
  /**
   * <code>.paperatus.Mapping mapping = 2;</code>
   * @return The mapping.
   */
  @java.lang.Override
  public com.paperatus.matrix.proto.Mapping getMapping() {
    return mapping_ == null ? com.paperatus.matrix.proto.Mapping.getDefaultInstance() : mapping_;
  }
  /**
   * <code>.paperatus.Mapping mapping = 2;</code>
   */
  @java.lang.Override
  public com.paperatus.matrix.proto.MappingOrBuilder getMappingOrBuilder() {
    return getMapping();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ledData_ != null) {
      output.writeMessage(1, getLedData());
    }
    if (mapping_ != null) {
      output.writeMessage(2, getMapping());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ledData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLedData());
    }
    if (mapping_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMapping());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.paperatus.matrix.proto.Setup)) {
      return super.equals(obj);
    }
    com.paperatus.matrix.proto.Setup other = (com.paperatus.matrix.proto.Setup) obj;

    if (hasLedData() != other.hasLedData()) return false;
    if (hasLedData()) {
      if (!getLedData()
          .equals(other.getLedData())) return false;
    }
    if (hasMapping() != other.hasMapping()) return false;
    if (hasMapping()) {
      if (!getMapping()
          .equals(other.getMapping())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLedData()) {
      hash = (37 * hash) + LEDDATA_FIELD_NUMBER;
      hash = (53 * hash) + getLedData().hashCode();
    }
    if (hasMapping()) {
      hash = (37 * hash) + MAPPING_FIELD_NUMBER;
      hash = (53 * hash) + getMapping().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.paperatus.matrix.proto.Setup parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.paperatus.matrix.proto.Setup parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.paperatus.matrix.proto.Setup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.paperatus.matrix.proto.Setup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.paperatus.matrix.proto.Setup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.paperatus.matrix.proto.Setup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.paperatus.matrix.proto.Setup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.paperatus.matrix.proto.Setup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.paperatus.matrix.proto.Setup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.paperatus.matrix.proto.Setup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.paperatus.matrix.proto.Setup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.paperatus.matrix.proto.Setup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.paperatus.matrix.proto.Setup prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code paperatus.Setup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:paperatus.Setup)
      com.paperatus.matrix.proto.SetupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.paperatus.matrix.proto.LedControlProto.internal_static_paperatus_Setup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.paperatus.matrix.proto.LedControlProto.internal_static_paperatus_Setup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.paperatus.matrix.proto.Setup.class, com.paperatus.matrix.proto.Setup.Builder.class);
    }

    // Construct using com.paperatus.matrix.proto.Setup.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (ledDataBuilder_ == null) {
        ledData_ = null;
      } else {
        ledData_ = null;
        ledDataBuilder_ = null;
      }
      if (mappingBuilder_ == null) {
        mapping_ = null;
      } else {
        mapping_ = null;
        mappingBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.paperatus.matrix.proto.LedControlProto.internal_static_paperatus_Setup_descriptor;
    }

    @java.lang.Override
    public com.paperatus.matrix.proto.Setup getDefaultInstanceForType() {
      return com.paperatus.matrix.proto.Setup.getDefaultInstance();
    }

    @java.lang.Override
    public com.paperatus.matrix.proto.Setup build() {
      com.paperatus.matrix.proto.Setup result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.paperatus.matrix.proto.Setup buildPartial() {
      com.paperatus.matrix.proto.Setup result = new com.paperatus.matrix.proto.Setup(this);
      if (ledDataBuilder_ == null) {
        result.ledData_ = ledData_;
      } else {
        result.ledData_ = ledDataBuilder_.build();
      }
      if (mappingBuilder_ == null) {
        result.mapping_ = mapping_;
      } else {
        result.mapping_ = mappingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.paperatus.matrix.proto.Setup) {
        return mergeFrom((com.paperatus.matrix.proto.Setup)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.paperatus.matrix.proto.Setup other) {
      if (other == com.paperatus.matrix.proto.Setup.getDefaultInstance()) return this;
      if (other.hasLedData()) {
        mergeLedData(other.getLedData());
      }
      if (other.hasMapping()) {
        mergeMapping(other.getMapping());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.paperatus.matrix.proto.Setup parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.paperatus.matrix.proto.Setup) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.paperatus.matrix.proto.LedData ledData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.paperatus.matrix.proto.LedData, com.paperatus.matrix.proto.LedData.Builder, com.paperatus.matrix.proto.LedDataOrBuilder> ledDataBuilder_;
    /**
     * <code>.paperatus.LedData ledData = 1;</code>
     * @return Whether the ledData field is set.
     */
    public boolean hasLedData() {
      return ledDataBuilder_ != null || ledData_ != null;
    }
    /**
     * <code>.paperatus.LedData ledData = 1;</code>
     * @return The ledData.
     */
    public com.paperatus.matrix.proto.LedData getLedData() {
      if (ledDataBuilder_ == null) {
        return ledData_ == null ? com.paperatus.matrix.proto.LedData.getDefaultInstance() : ledData_;
      } else {
        return ledDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.paperatus.LedData ledData = 1;</code>
     */
    public Builder setLedData(com.paperatus.matrix.proto.LedData value) {
      if (ledDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ledData_ = value;
        onChanged();
      } else {
        ledDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.paperatus.LedData ledData = 1;</code>
     */
    public Builder setLedData(
        com.paperatus.matrix.proto.LedData.Builder builderForValue) {
      if (ledDataBuilder_ == null) {
        ledData_ = builderForValue.build();
        onChanged();
      } else {
        ledDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.paperatus.LedData ledData = 1;</code>
     */
    public Builder mergeLedData(com.paperatus.matrix.proto.LedData value) {
      if (ledDataBuilder_ == null) {
        if (ledData_ != null) {
          ledData_ =
            com.paperatus.matrix.proto.LedData.newBuilder(ledData_).mergeFrom(value).buildPartial();
        } else {
          ledData_ = value;
        }
        onChanged();
      } else {
        ledDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.paperatus.LedData ledData = 1;</code>
     */
    public Builder clearLedData() {
      if (ledDataBuilder_ == null) {
        ledData_ = null;
        onChanged();
      } else {
        ledData_ = null;
        ledDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.paperatus.LedData ledData = 1;</code>
     */
    public com.paperatus.matrix.proto.LedData.Builder getLedDataBuilder() {
      
      onChanged();
      return getLedDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.paperatus.LedData ledData = 1;</code>
     */
    public com.paperatus.matrix.proto.LedDataOrBuilder getLedDataOrBuilder() {
      if (ledDataBuilder_ != null) {
        return ledDataBuilder_.getMessageOrBuilder();
      } else {
        return ledData_ == null ?
            com.paperatus.matrix.proto.LedData.getDefaultInstance() : ledData_;
      }
    }
    /**
     * <code>.paperatus.LedData ledData = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.paperatus.matrix.proto.LedData, com.paperatus.matrix.proto.LedData.Builder, com.paperatus.matrix.proto.LedDataOrBuilder> 
        getLedDataFieldBuilder() {
      if (ledDataBuilder_ == null) {
        ledDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.paperatus.matrix.proto.LedData, com.paperatus.matrix.proto.LedData.Builder, com.paperatus.matrix.proto.LedDataOrBuilder>(
                getLedData(),
                getParentForChildren(),
                isClean());
        ledData_ = null;
      }
      return ledDataBuilder_;
    }

    private com.paperatus.matrix.proto.Mapping mapping_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.paperatus.matrix.proto.Mapping, com.paperatus.matrix.proto.Mapping.Builder, com.paperatus.matrix.proto.MappingOrBuilder> mappingBuilder_;
    /**
     * <code>.paperatus.Mapping mapping = 2;</code>
     * @return Whether the mapping field is set.
     */
    public boolean hasMapping() {
      return mappingBuilder_ != null || mapping_ != null;
    }
    /**
     * <code>.paperatus.Mapping mapping = 2;</code>
     * @return The mapping.
     */
    public com.paperatus.matrix.proto.Mapping getMapping() {
      if (mappingBuilder_ == null) {
        return mapping_ == null ? com.paperatus.matrix.proto.Mapping.getDefaultInstance() : mapping_;
      } else {
        return mappingBuilder_.getMessage();
      }
    }
    /**
     * <code>.paperatus.Mapping mapping = 2;</code>
     */
    public Builder setMapping(com.paperatus.matrix.proto.Mapping value) {
      if (mappingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mapping_ = value;
        onChanged();
      } else {
        mappingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.paperatus.Mapping mapping = 2;</code>
     */
    public Builder setMapping(
        com.paperatus.matrix.proto.Mapping.Builder builderForValue) {
      if (mappingBuilder_ == null) {
        mapping_ = builderForValue.build();
        onChanged();
      } else {
        mappingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.paperatus.Mapping mapping = 2;</code>
     */
    public Builder mergeMapping(com.paperatus.matrix.proto.Mapping value) {
      if (mappingBuilder_ == null) {
        if (mapping_ != null) {
          mapping_ =
            com.paperatus.matrix.proto.Mapping.newBuilder(mapping_).mergeFrom(value).buildPartial();
        } else {
          mapping_ = value;
        }
        onChanged();
      } else {
        mappingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.paperatus.Mapping mapping = 2;</code>
     */
    public Builder clearMapping() {
      if (mappingBuilder_ == null) {
        mapping_ = null;
        onChanged();
      } else {
        mapping_ = null;
        mappingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.paperatus.Mapping mapping = 2;</code>
     */
    public com.paperatus.matrix.proto.Mapping.Builder getMappingBuilder() {
      
      onChanged();
      return getMappingFieldBuilder().getBuilder();
    }
    /**
     * <code>.paperatus.Mapping mapping = 2;</code>
     */
    public com.paperatus.matrix.proto.MappingOrBuilder getMappingOrBuilder() {
      if (mappingBuilder_ != null) {
        return mappingBuilder_.getMessageOrBuilder();
      } else {
        return mapping_ == null ?
            com.paperatus.matrix.proto.Mapping.getDefaultInstance() : mapping_;
      }
    }
    /**
     * <code>.paperatus.Mapping mapping = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.paperatus.matrix.proto.Mapping, com.paperatus.matrix.proto.Mapping.Builder, com.paperatus.matrix.proto.MappingOrBuilder> 
        getMappingFieldBuilder() {
      if (mappingBuilder_ == null) {
        mappingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.paperatus.matrix.proto.Mapping, com.paperatus.matrix.proto.Mapping.Builder, com.paperatus.matrix.proto.MappingOrBuilder>(
                getMapping(),
                getParentForChildren(),
                isClean());
        mapping_ = null;
      }
      return mappingBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:paperatus.Setup)
  }

  // @@protoc_insertion_point(class_scope:paperatus.Setup)
  private static final com.paperatus.matrix.proto.Setup DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.paperatus.matrix.proto.Setup();
  }

  public static com.paperatus.matrix.proto.Setup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Setup>
      PARSER = new com.google.protobuf.AbstractParser<Setup>() {
    @java.lang.Override
    public Setup parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Setup(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Setup> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Setup> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.paperatus.matrix.proto.Setup getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

