// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: led_control.proto

package com.paperatus.matrix.proto;

public interface SetupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paperatus.Setup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.paperatus.LedData ledData = 1;</code>
   * @return Whether the ledData field is set.
   */
  boolean hasLedData();
  /**
   * <code>.paperatus.LedData ledData = 1;</code>
   * @return The ledData.
   */
  com.paperatus.matrix.proto.LedData getLedData();
  /**
   * <code>.paperatus.LedData ledData = 1;</code>
   */
  com.paperatus.matrix.proto.LedDataOrBuilder getLedDataOrBuilder();

  /**
   * <code>.paperatus.Mapping mapping = 2;</code>
   * @return Whether the mapping field is set.
   */
  boolean hasMapping();
  /**
   * <code>.paperatus.Mapping mapping = 2;</code>
   * @return The mapping.
   */
  com.paperatus.matrix.proto.Mapping getMapping();
  /**
   * <code>.paperatus.Mapping mapping = 2;</code>
   */
  com.paperatus.matrix.proto.MappingOrBuilder getMappingOrBuilder();
}
